### PR TITLE
Add the ability to parse xml without namespaces/key prefix

### PR DESCRIPTION
**Pull request by Kazakbai**
Hi Nhu Nguyen, recently performing the task of compressing xml data from one service and a problem occurred when parsing data. namely with key prefixes. They changed from time to time, for example, the key was <d4p1: Title>, after a time it changed to <d6p2: Title>, etc. Therefore there was a need to parse without key prefixes.

### CODE REVIEW

**Comment by nhu313** [comment]
Hi @Kazakbay, thank you for the contribution. I love getting PR ❤️  Do you mind giving me a sample of your `xml` and the expected result so I can write up a test for it. While I am making an update, I'm going to add to your PR so it will handle the comments too. Thanks again for the PR.

**Comment by Kazakbai** [comment]
Hi @nhu313, added to README how to parse xml without namespaces and there is an sample with xml

**Comment by nhu313** [comment]
Hi @Kazakbay, thanks for the quick reply. The code looks good. I am going to add more to it and make send second params an option map so I can add in the functionality to parse comments. After that, I should be able to merge the code in this weekend. Thank you again for the contribution :)

**Comment by Kazakbai** [comment]
Good luck!

**Pull request merged**
